### ISSUE TITLE
functionalANOVA depends on vars order 

### ISSUE THREAD

**Issue by christophM** [zmjones/fanova#1]
Hey Zach

The computation of effects for functionalANOVA differs depending on the order of the features in the "vars" parameter. Is this expected behaviour? Then I am misunderstanding the method. 

Here is some code to reproduce the issue: 

```r
set.seed(42)
dt = data.frame(x1 = rnorm(100), x2 = rnorm(100))
dt$y = dt$x1 + 2 * dt$x2 + rnorm(100)
mod = lm(y ~ x1 + x2, data = dt)
f12 = functionalANOVA(dt, vars = c("x1", "x2"), model = mod)
ggplot(f12[f12$effect == "x1:x2"]) + geom_tile(aes(x = x1, y = x2, fill = f))
f21 = functionalANOVA(dt, vars = c("x2", "x1"), model = mod)
ggplot(f21[f21$effect == "x2:x1"]) + geom_tile(aes(x = x1, y = x2, fill = f))
```

![image](https://user-images.githubusercontent.com/1632100/39034029-1b133a3a-4475-11e8-89d6-3c7d20e7b09f.png)
![image](https://user-images.githubusercontent.com/1632100/39034031-1d57b8fc-4475-11e8-94a7-0023e309a258.png)

**Comment by christophM** [comment]
Also I would have expected that for a linear model, the interaction effects are always zero.

**Comment by christophM** [comment]
I looked through the code and the paper. 
Could it be, that the constraints are not implemented?
![screenshot from 2018-04-20 10-50-38](https://user-images.githubusercontent.com/1632100/39041242-af63faf4-4488-11e8-83d9-d823d368832a.png)

In the fanova package there is just a call to `glmnet`, but the constraints that some of the sums have to be zero is missing.

**Comment by zmjones** [comment]
you are right. this implements the simple method he describes, which is a standard anova fit to the design matrix he describes. i'm working on implementing this version but haven't been able to get it right yet.

i found two bugs, both of which are fixed now. one was from setting vars to be all the available covariates in the model and the other was a naming bug which i think came from a glmnet api change. your example produces the expected output now.

however neither of the graphs you plotted show an interaction between x1 and x2. so that is correct. you can see that neither variable affects the function values of the other in the plots. however in both plots. what you were actually looking at was an estimate of the marginal effect of one of the variables.

**Comment by christophM** [comment]
Thanks!
